### PR TITLE
Add library version and name for Hugging Face download stats

### PR DESCRIPTION
**Pull request by osanseviero**
This will enable Asteroid-specific download stats.

FYI @julien-c

### CODE REVIEW

**Comment by mpariente** [comment]
Thanks for the PR, that would be nice indeed! 
The minimum version in the requirements ([here](https://github.com/asteroid-team/asteroid/blob/master/requirements/torchhub.txt)) is 0.0.2, is that enough? 

Could you lint the PR please? I'll merge right after. 
Thanks !

**Comment by osanseviero** [comment]
Done :)

Yes, `cached_download` had the library name/version params since the beginning, so it should work fine with early versions(@LysandreJik please correct me if I'm wrong :) )

**Comment by LysandreJik** [comment]
You are correct!

**Comment by mpariente** [comment]
Thanks to both of you

**Pull request merged**
