### PR TITLE
DCUnet on musdb18

### PR DESCRIPTION
**Pull request by lubacien**
Here is my pull request, it's the first time I do this so I'm not sure I'm doing it correctly, sorry. The DCUNet recipe is working for musdb18 dataset.
Lucien

### CODE REVIEW

**Comment by mpariente** [comment]
Thanks a lot Lucien, this is great ! 

Few things before I make a more in-depth review: 
- If you copy paste code from somewhere, you need to add a link to it, and preferably to the original License. 
- Have a look at `black` and format your code before committing. There is a note about it in the contribution guide. 
- If you add new arguments to a function, you have to make sure to keep the original behaviour so that things stay backwards compatible (e.g the new `mono` argument should be False if I checked correctly). 
- The `utils` folder should be symlinked instead of copied: use `ln -s ../../wham/utils .` to do that (after removing the current copied folder). 
- The beginning of the recipe should contain the steps to acquire and preprocess the data. It seems the WHAM stages were copied, which is not appropriate. 

If you have specific questions about implementation details, feel free to ask directly by adding comments in the code, we'll answer all of them.

**Comment by faroit** [comment]
@lubacien cool to see a recipe. Can you report the `museval` scores?

**Comment by lubacien** [comment]
Thanks, I'll look at all this. 
@faroit I'll put my results in the readme as soon as my evaluation is over. My dataset is not exactly musdb though, it only has the same shape, but results should be similar.

**Comment by mpariente** [comment]
@faroit would you like to add `museval` support to the `get_metrics` function?

**Comment by faroit** [comment]
> @faroit would you like to add `museval` support to the `get_metrics` function?

since `museval` is api compatible with `mir_eval` that should be quick, right. But I don't want to spend too much time on `museval` since its going to be refactored anyway soon

**Comment by faroit** [comment]
>  @faroit I'll put my results in the readme as soon as my evaluation is over. My dataset is not exactly musdb though, it only has the same shape, but results should be similar.

Sure, no worries. I just would propose to not add models that perform worse on MUSDB18 than baselines such as `open-unmix` or `demucs`.

**Comment by mpariente** [comment]
Let's start with this recipe, and we'll see what it becomes if the results are too poor. 
This is just an example usage of MUSDB and people have been asking for one for a while now, so already having this is super great! Thanks @lubacien

**Comment by faroit** [comment]
> This is just an example usage of MUSDB and people have been asking for one for a while now,

yes, I know... open-unmix will follow soon ;-)

**Comment by mpariente** [comment]
This recipe requires manual download of the data (with permission), so the download step has to be manual. There is no preprocessing. 

I wonder, should this be our first all-python recipe? @jonashaag I'd like your opinion on that. At least, we'll see what it looks like.

**Comment by lubacien** [comment]
Here are the first results, not looking great, results for each track will follow but it's not working right now:
Overall metrics :
{'sar': 7.677097041220532,
 'sar_imp': -209.51092946796453,
 'sdr': 0.8776128026828975,
 'sdr_imp': 6.523041722406209,
 'si_sdr': 0.400428520408459,
 'si_sdr_imp': 6.069929884043522,
 'sir': 3.387571293027092,
 'sir_imp': 9.033000212750402,
 'stoi': 0.4542502477583873,
 'stoi_imp': 0.005655757621438261}

**Comment by mpariente** [comment]
@faroit what do you think about the results? Did you run eval with those metrics for UMX?

**Comment by faroit** [comment]
> @faroit what do you think about the results? Did you run eval with those metrics for UMX?

no, i never did and most of them wouldn't make much sense on music signals, but I sure, i could. 

* how are the frames aggregated?
* what is the evaluation window?

@lubacien can you also provide museval scores?

**Comment by lubacien** [comment]
I'm sorry, there was a mistake in the previous evaluation, not all the tracks were evaluated. Here are the correct results:

Overall metrics :                                                                                                                                              
{'sar': 7.852583689561572,                                                                                                                                     
 'sar_imp': -207.138435766525,                                                                                                                                 
 'sdr': 0.9848852416958992,                                                                                                                                    
 'sdr_imp': 6.777304418029081,                                                                                                                                 
 'si_sdr': 0.4808705825731158,                                                                                                                                 
 'si_sdr_imp': 6.301444532349706,                                                                                                                              
 'sir': 3.4675965586933986,                                                                                                                                    
 'sir_imp': 9.260015735026574,                                                                                                                                 
 'stoi': 0.4615495954502384,                                                                                                                                   
 'stoi_imp': 0.005292239396206363}

The museval scores will be there soon.

**Comment by lubacien** [comment]
Here are the results, not on MUSDB directly but on a similar dataset. It's much worse than what I had with open-unmix.. It's interesting that the SI-SDR is not too bad for bass but the SDR is so low?
SI-SDR:
vocals  -0.30114007953227095
drums   -2.932394022833572
bass    6.607583086456335
other   -5.500816254150754
Aggrated Scores (median over frames, median over tracks)
vocals          ==> SDR:   2.018  SIR:   1.259  ISR:   7.527  SAR:   7.898  
drums           ==> SDR:   1.675  SIR:   0.250  ISR:   3.307  SAR:   2.397  
bass            ==> SDR:  -3.981  SIR:  10.892  ISR:  -3.866  SAR:   8.879  
other           ==> SDR:  -4.529  SIR:  -3.358  ISR:  -3.569  SAR:   6.061

**Comment by lubacien** [comment]
Actually I realise the training was only done on 80 songs. I'll try to rerun this on more data.

**Comment by lubacien** [comment]
I was running the museval evaluation with a separate script, but I'll add the museval scores now to the eval script.

**Comment by lubacien** [comment]
New scores, training on 200 songs, much better (although still not as good as open unmix for the same dataset) 

Overall metrics :
{'sar': 6.322532635070612,
 'sar_imp': -208.66848682101593,
 'sdr': 2.74920451292428,
 'sdr_imp': 8.541623689257461,
 'si_sdr': 2.0629611066542566,
 'si_sdr_imp': 7.883535056430847,
 'sir': 7.209730675077486,
 'sir_imp': 13.00214985141066,
 'stoi': 0.4967561176492682,
 'stoi_imp': 0.04049876159523617}
SI-SDR
vocals  1.3440309134104997
drums   -0.3779813331700441
bass    8.180581247216029
other   -4.211183894330432
Aggrated Scores (median over frames, median over tracks)
vocals          ==> SDR:   3.598  SIR:   4.840  ISR:   6.172  SAR:   5.990  
drums           ==> SDR:   2.656  SIR:   5.591  ISR:   5.565  SAR:   2.349  
bass            ==> SDR:   8.330  SIR:  12.162  ISR:  10.486  SAR:   9.113  
other           ==> SDR:  -3.276  SIR:   0.626  ISR:  -2.803  SAR:   2.943

**Comment by faroit** [comment]
@lubacien why not train on MUSDB18 train first, report those numbers and then fine-tune/continue with your extra-data to improve?

**Comment by lubacien** [comment]
I don't have MUSDB yet, I'll ask for it and do this.

**Comment by faroit** [comment]
> I don't have MUSDB yet, I'll ask for it and do this.

Oh, i thought this was already MUSDB18 test performance.

**Comment by lubacien** [comment]
I'm sorry, I had some problems trying to make this work and then started working on something else instead, I'll try to finish this later if I have time..

**Pull request closed without merging**
