### PR TITLE
Add MetricTracker

### PR DESCRIPTION
**Pull request by mpariente**
Just because it's less code duplicate and it seems useful. 
Inspired by the `WerTracker` in #329.

### CODE REVIEW

**Comment by mpariente** [comment]
@JorisCos @jonashaag some feedback?

**Comment by jonashaag** [comment]
VERY quick code review, looks ok, maybe remove the dumping (CSV/JSON) code entirely and let the user to it? It's only an additional `.to_csv()` call to be done by the user

**Comment by jonashaag** [comment]
At some point I will try to think of an integration of this into `System` for live metrics. Right now I have something similar in my recipes

**Comment by mpariente** [comment]
> At some point I will try to think of an integration of this into `System` for live metrics. Right now I have something similar in my recipes

Yes, using Lightning for evaluation would really make things simple, and help us get rid on bash..

**Comment by mpariente** [comment]
Thanks for the review.

**Comment by mpariente** [comment]
Resolved conflicts and clean things up.

We should converge on a format for the output (dataframe, aggregate final results in dictionnary, dump to JSON, autogenerate markdown table).

**Pull request merged**
