### PR TITLE
Fix unit-tests

### PR DESCRIPTION
**Pull request by JorisCos**
This fixes unit tests.
The problem was coming from PL version which is  1.5.4 now

### CODE REVIEW

**Comment by jonashaag** [comment]
Does this break older PL versions though? We have `>=1.01` in the requirements.

**Comment by mpariente** [comment]
Thanks for fixing the tests !

**Comment by mpariente** [comment]
It probably does break previous versions. 
So let's fix the PL version under the backward incompatible change, make a release, and then we'll upgrade PL and drop previous versions in a new release, does this sound ok?

**Comment by jonashaag** [comment]
Or we could add a manual check to that particular module only. Probably using this code https://github.com/PyTorchLightning/pytorch-lightning/blob/f63222d9663e6af06738c64744522acf7cb20221/pytorch_lightning/utilities/imports.py#L46

**Comment by mpariente** [comment]
Just for reference, the deprecation cycle started [here](https://github.com/PyTorchLightning/pytorch-lightning/pull/7339) in 1.3 and was merged [here](https://github.com/PyTorchLightning/pytorch-lightning/pull/8587) for 1.5. 

I haven't been following PL too much, my bad

**Comment by mpariente** [comment]
> Or we could add a manual check to that particular module only. Probably using this code https://github.com/PyTorchLightning/pytorch-lightning/blob/f63222d9663e6af06738c64744522acf7cb20221/pytorch_lightning/utilities/imports.py#L46

Yes, that's also ok. For now, I'll just fix PL's version.

**Pull request closed without merging**
