### PR TITLE
Fix inconsistent devices for tensors

### PR DESCRIPTION
**Pull request by hangtingchen**
Fix inconsistent devices for tensors

### CODE REVIEW

**Comment by jonashaag** [comment]
Looks good, can you add a test?

**Comment by mpariente** [comment]
IMO, we can merge without a test.

**Comment by jonashaag** [comment]
Ah, since we only have a single PyTorch device in CI, it's kind of pointless anyways. I was wondering why this isn't tested already, but we always only ever test with the default device in the first place. At some point it would be really great to add a second the device to CI and also run all of the tests on CPU and CUDA.

**Comment by hangtingchen** [comment]
The bug was found when I train the network on GPU, but `cnt ` was placed on CPU in default. It is a good idea to add a second device to CI. Maybe this can be done in another PR.

**Comment by jonashaag** [comment]
> It is a good idea to add a second device to CI. Maybe this can be done in another PR.

Unfortunately we don't have GPU support in CI :(

Will merge this fix, thanks for the patch.

**Comment by mpariente** [comment]
Yes, no GPU on CI. Maybe we can emulate another device? It might be too much work. 
I don't know whether CircleCI or drone provide free GPU CI, we might want to have a look.

**Pull request merged**
